### ISSUE TITLE
Team Biography

### ISSUE THREAD

**Issue by BranicYeti** [Zyncco/Website#3]
As discussed during the [second meeting](https://docs.google.com/document/d/1KkJyxMg-nDGV_hejDSqJLGlgSk8QhyT0hEIJwv9q2aI/edit), we are going to have a section of the [static site](https://zync.co/) introducing the team. I don't really know any of you too well, so I don't know what to put. Please provide me (via comment here) with a picture / avatar, your preferred handle, your title relating to this project in your words (developer, designer, code monkey, whatever) and 1-3 sentences about you. If you would like links to your github profile, twitter or other external site included, please provide those too. I will find appropriate sprites to accompany them.

Please keep everything SFW, preferably G- or U-rated. Whilst unlikely, there's a chance that our userbase will be younger than we are.

Once you have done that, feel free to unassign yourself.

Thank you.

Edit: At request of Amir, please provide the name you wish to have listed (first or full, your choice), and optionally your online handle. For example, I have put "Brandon (Yeti)" and I assume Amir will put "Amir Omidi".

**Comment by BranicYeti** [comment]
![yeti-dark](https://cloud.githubusercontent.com/assets/1971818/23827487/9456d09e-06ac-11e7-8dee-a46abc44cbdc.png)

Handle:  
`Brandon (Yeti)`

Title:  
`Developer`

About:  
`I am a self-taught, self-employed software developer living in the United Kingdom, primarily working with command line / backend applications. I know Java, C#, Python and a handful of other non-programming languages.`

Sites:
- [GitHub](https://github.com/BranicYeti)

**Comment by aaomidi** [comment]
Name:
`Amir Omidi`

Handle:
`aaomidi`

Title:
`Project Lead and Developer`

About:
`I'm a student studying Computer Sciences at Drexel University. I love trying out new technologies, frameworks, and gadgets. My career goal is to be a software engineer at a top tech firm.`

Sites:
- [GitHub](https://github.com/aaomidi)
- [Personal Site](https://aaomidi.com)

[Avatar](https://i.imgur.com/l6LSheH.jpg)

**Comment by mkotb** [comment]
Handle:
`[A]Mazen Kotb`

Title:
`Java Developer`

About:
`I'm currently a Canadian Software Engineer and have been programming for 6 years since I was young. Although I've stuck in my hand in around everything, my expertise primarily resides in using JVM languages for backend infrastructures. Outside of Computer Science, I love writing, talking (in front of large groups), and exploring around Vancouver.  If you want to chat, feel free to hit me up a message on Telegram.`

Sites:
- [GitHub](https://github.com/mkotb)
- [Telegram](https://t.me/mazenk)

[Avatar](https://goo.gl/photos/UCybZwtJhURcDTPKA)

**Comment by Vilsol** [comment]
Handle:
`Vilsol`

Title:
`Resident Cunt`

About:
`A software engineer with a passion for virtualization. Mostly spent time as a full-stack developer in many languages, frameworks and platforms, but recently more focused on systems, operations and infrastructure. Left university to pursue my career as well as many side projects including this one.`

**Comment by BranicYeti** [comment]
@devmattrick @DarkSeraphim 

Still waiting on your profiles. Please provide something when you have a spare 5-10 minutes. Thanks

**Comment by devmattrick** [comment]
Handle:
`mattrick`

Title:
`Developer McDeveloperface`

About:
`I'm a designer and developer from sunny Southern California. I mostly work with web stuff.`

Sites:
- [GitHub](https://github.com/devmattrick)
- [Keybase](https://keybase.io/mattrick)
- [Twitter](https://twitter.com/devmattrick)

[Avatar](https://avatars3.githubusercontent.com/u/5848320?v=3)

**Comment by DarkSeraphim** [comment]
Handle:
`Mark Hendriks`

Title:
`Backend Developer`

About:
`I'm a Computer Science student at University of Technology in Eindhoven, mainly spending my time experimenting with new solutions and new languages, always aiming for fast and scale-able`

Sites:
- [Github](https://github.com/DarkSeraphim)
- [LinkedIn](https://linkedin.com/in/mark-hendriks-60029391)
