### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by BranicYeti** [Zyncco/Website#4]
CSS is being cached hard. Since GitHub pages is designed to host dynamically-built content, I'm blaming CloudFlare. We want zero caching happening on the apex site, and TBD caching on the assets site.

**Comment by BranicYeti** [comment]
@aaomidi

SSL is no longer working for `zync.co`. I assume this is because you disabled CloudFlare on the domain to prevent caching for now. Is this issue okay to be closed, or are you leaving it open as a reminder to re-enable CloudFlare later?

**Comment by aaomidi** [comment]
The https was "fake https", we're going to need to have a proper hosting for it to get proper https.

**Comment by BranicYeti** [comment]
The HTTPS (or lack thereof) wasn't the issue, I was just using it as an indicator that CloudFlare had been disabled, meaning that this issue had been resolved. I didn't know if you were keeping this issue open as a reminder to re-enable it when development is finished, or if it could be closed.

On the topic of HTTPS and CloudFlare having their funny little system. This site will be mostly static content, and the dynamic content will be nothing important, just me being lazy and avoiding having to manually update HTML. Have I mentioned that I love Jekyll? No authentication will be processed here, or on the site that will host the API spec. In my opinion, they don't need HTTPS at all, but it might be an idea to just use CloudFlare's 50/50 thing so we have the little green padlock. The API, however, will need properly securing for obvious reasons.

**Comment by aaomidi** [comment]
See, the issue is that I either get to choose no cloudflare or cloudflare full system. I'll choose the full cloudflare system for now.

**Comment by BranicYeti** [comment]
For development, we want no CloudFlare on account of caching being a hinderance, but after that, I agree with your decision. Maybe by the time we launch, there will be more we can do whilst keeping the server cost at 0.

**Comment by BranicYeti** [comment]
Closing this since cache is no longer hindering development and we're probably moving off of gh-pages
