### ISSUE TITLE
Host website on firebase

### ISSUE THREAD

**Issue by aaomidi** [Zyncco/Website#5]
Use firebase hosting to host website.

**Comment by BranicYeti** [comment]
Will it handle the bandwidth?
Does it support Jekyll?

**Comment by aaomidi** [comment]
Not sure about Jekyll.
I'll find a good way to handle bandwidth, probably cloudflare.

**Comment by BranicYeti** [comment]
For the time being, please keep it available on github pages for development. If we can get Jekyll working on Firebase, it'll require some additional tweaks in the config that Github handles for us. We should be able to install whatever technology we want in terms of web hosting, so I'm hopeful. If not, we might need to use Travis to compile the Jekyll to HTML and SASS to CSS and deploy it that way.

**Comment by aaomidi** [comment]
Development can happen here, however the domain can't point to two places at the same time.

**Comment by aaomidi** [comment]
Auto Deploy Complete

https://github.com/Zyncco/Website/commit/eb7f2e634df749782da2d62efbc268710bcda283

https://github.com/Zyncco/Website/commit/98cd8f8f0d173db34bdd6c2f2249a1bec770d864

https://github.com/Zyncco/Website/commit/fe1d96c3c88a43b373eac26d6ab82c1b8cb1b87d
