### ISSUE TITLE
Firebase SSL

### ISSUE THREAD

**Issue by BranicYeti** [Zyncco/Website#6]
Our SSL is valid on zync.co, which is fantastic. Chrome and Firefox both love it. However, our certificate is issued to glowsync.com, which is another site being hosted on Firebase. No clue what's going on there, but it might be something we have to look into.

![image](https://cloud.githubusercontent.com/assets/1971818/24067384/d9e27f66-0b73-11e7-80de-42f12d898739.png)

**Comment by aaomidi** [comment]
Wow, that's fucking weird.

**Comment by aaomidi** [comment]
Contacted google about this issue, will update once I hear a response from them

**Comment by aaomidi** [comment]
Working as intended. https://firebase.google.com/docs/hosting/custom-domain#wait-for-ssl-certificate-provisioning
